//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ap2D.rc
//
#define ID_BUT_SEL_COLOR                3
#define ID_BUTTON_RECOVERY              3
#define ID_BUT_EDIT_DB                  3
#define IDCANCEL2                       3
#define ID_BUT_REPLACE                  3
#define IDCANCEL3                       4
#define ID_DELETE                       4
#define IDCANCEL4                       5
#define IDD_ABOUTBOX                    100
#define IDD_DLG_EDIT_HOTKEY             102
#define IDR_MAINFRAME                   128
#define IDR_AP2DTYPE                    129
#define IDB_GENERAL                     130
#define IDD_DLG_LOGIN                   130
#define IDD_DLG_PROJECT_MGR             131
#define IDD_PAGE_COMMON                 132
#define IDD_DLG_COMPARE                 133
#define IDD_DLG_FILE_MGR                134
#define IDD_DLG_DIM_NAME_SET            135
#define IDD_DLG_SELECT_NAME             136
#define IDD_DLG_SIGN_REPLACE            137
#define IDD_DLG_BLOCK_MANAGE            138
#define IDD_DLG_SELECT_TABLE_TEXT       140
#define IDD_DLG_PRO_PATHS_SAVE          141
#define IDD_DLG_JOINT_DB                142
#define IDD_DLG_SETUP                   143
#define IDR_TOOLBAR_SNAP                145
#define IDR_TOOLBAR_EDIT                154
#define IDB_CURRENT                     177
#define IDB_OPEN                        178
#define IDB_PROJECT                     179
#define IDI_ICON1                       180
#define IDI_ICON2                       181
#define IDI_ICON3                       182
#define IDI_ICON4                       183
#define IDB_BMP_EDIT                    203
#define IDB_BMP_CREATE                  204
#define IDB_BMP_SNAP                    207
#define IDB_BMP_ERROR                   208
#define IDD_DLG_APNET                   215
#define IDC_EDIT1                       1000
#define IDC_EDIT_PATH                   1000
#define IDC_EDIT_COL_NUM                1001
#define IDC_EDIT2                       1001
#define IDC_BUT_PATH                    1001
#define IDC_EDIT_PASSWORD               1001
#define IDC_EDIT_COL_DIS                1002
#define IDC_BN_DEFAULT                  1002
#define IDC_EDIT_TWO_PREFIX             1002
#define IDC_CHECK_COPY_TO               1002
#define IDC_BUT_LOAD_PATH               1002
#define IDC_EDIT_ANGLE                  1003
#define IDC_BN_ADVANCED                 1003
#define IDC_EDIT_TWO_POSTFIX            1003
#define IDC_EDIT_COPY_TO                1003
#define IDC_LIST_PROJECT                1004
#define IDC_EDIT_PRECISION              1004
#define IDC_RADIO_DATA                  1004
#define IDC_BN_OK                       1004
#define ID_BUT_NEW                      1005
#define ID_BUT_NEW_PROJECT              1005
#define IDC_LIST_NAMES                  1005
#define IDC_RADIO_PREFIX                1005
#define IDC_EDIT_WIDTH_FACTOR           1005
#define ID_BUT_EDIT                     1006
#define ID_BUT_EDIT_PROJECT             1006
#define IDC_EDIT_TXT1                   1006
#define IDC_EDIT_POSTFIX                1006
#define IDR_TOOLBAR_ENTITY              1007
#define ID_BUT_DELETE                   1007
#define ID_BUT_DELETE_PROJECT           1007
#define IDC_EDIT_TXT2                   1007
#define IDC_BUT_COPY_TO_PATH            1007
#define ID_BUT_CLOSE                    1008
#define IDB_CHANGE                      1008
#define IDC_RADIO_NO                    1008
#define ID_BUT_OPEN                     1009
#define IDR_TOOLBAR_LAYER               1009
#define IDC_CHECK_NAMES                 1009
#define ID_COMBO_HIT                    1009
#define IDC_LIST_COMPANY                1010
#define IDR_TOOLBAR_RIGHT               1010
#define IDC_EDIT_DELETE                 1010
#define ID_BUT_NEW2                     1011
#define IDC_CHECK_PART                  1011
#define ID_BUT_NEW_COMPANY              1011
#define IDR_TOOLBAR_COMBO               1011
#define ID_COMBO_CBK                    1011
#define IDC_BUT_DELETE                  1011
#define ID_BUT_EDIT2                    1012
#define ID_BUT_MERGE                    1012
#define ID_BUT_EDIT_COMPANY             1012
#define ID_BUT_COMBINATION              1012
#define ID_BUT_DELETE2                  1013
#define IDC_CHECK_CUT                   1013
#define ID_BUT_DEL_COMPANY              1013
#define ID_BUT_SET                      1013
#define IDR_MENU_CMD_MANAGE             1013
#define IDC_CHECK_MARK                  1014
#define IDR_MENU_TREE                   1014
#define ID_BUT_SAVE                     1014
#define IDC_CHECK_SHEET                 1015
#define ID_BUT_SAVE_PROJECT             1015
#define IDC_COMBO_TEXT_POS              1015
#define IDR_MENU_TREE_CHECK             1015
#define IDC_CHECK_VIEW                  1016
#define ID_BUT_DEL_TREE_INFO            1016
#define IDC_BUT_CHECK                   1016
#define IDC_CHECK_DIM                   1017
#define ID_BUT_PROJECT_PATH             1017
#define IDC_COMBO_FONT_STYLE            1017
#define ID_BUT_DOWN_LOAD                1018
#define IDC_EDIT_PROJECT_PATH           1018
#define IDC_CHECK_PART_SER              1019
#define IDC_RADIO_NO_CHANGE             1019
#define IDC_CHECK_CUT_SER               1020
#define IDC_RADIO_CHANGE_COLOR          1020
#define IDC_CHECK_MARK_SER              1021
#define IDC_RADIO_FILE_0_COLOR          1021
#define IDC_CHECK_SHEET_SER             1022
#define IDC_CHECK_RECORD                1022
#define IDC_RADIO_FILE_1_COLOR          1022
#define IDC_CHECK_VIEW_SER              1023
#define IDC_CHECK_INCLUDE_CURRENT       1023
#define IDC_CHECK_DIM_SER               1024
#define IDC_EDIT_ONE_PREFIX             1024
#define IDC_CHECK_APDIM_SER             1025
#define IDC_COMBO_LINE_STYLE            1025
#define IDC_EDIT_ONE_POSTFIX            1025
#define IDC_EDIT_CURRENT_TXT_VAL        1026
#define IDC_BUT_FILE_0                  1026
#define IDC_EDIT_TEXT                   1027
#define IDC_BUT_FILE_1                  1027
#define IDC_EDIT_FILE_0                 1028
#define IDC_EDIT_FILE_1                 1029
#define IDC_CHECK_FILE_0_COLOR          1030
#define IDC_CHECK_FILE_1_COLOR          1031
#define IDC_CHECK_RIGHT_MENU_SHOW       1031
#define IDC_COMBO_DIM_KIND              1032
#define IDC_BUT_TPL_SAVE                1033
#define IDC_BUT_TPL_READ                1034
#define IDC_BUT_TPL_DEL                 1034
#define IDC_COMBO_TPL_NAMES             1035
#define IDC_BUT_SAVE_AS                 1036
#define IDC_BUT_ADD_NAME                1037
#define IDC_BUT_SUB_NAME                1038
#define IDC_LIST_SET_INFO               1039
#define IDC_BUT_ADD_SIGN                1040
#define IDC_LIST_SIGNS                  1042
#define IDC_EDIT_TPL_NAME               1043
#define IDC_BUT_OK                      1044
#define IDC_BUT_APPLY                   1045
#define IDC_EDIT_NAME                   1045
#define IDC_COMBO_SIGNS                 1046
#define IDC_BUT_CANCEL                  1048
#define IDC_BUTTON_ADD                  1048
#define IDC_BUTTON_EDIT                 1049
#define IDC_BUTTON_DEL                  1050
#define IDC_STATIC_TEXT                 1051
#define IDC_STATIC_SIGNS                1052
#define IDC_LIST_BLOCK_NAMES            1054
#define IDC_COMBO_TEXT                  1056
#define IDC_CHECK_COLOR_FIND            1058
#define IDC_CHECK_TYPE_FIND             1059
#define IDC_LIST1                       1060
#define IDC_LIST_NUMBERS                1060
#define IDC_LIST_PRO_PAHTS_SAVE         1060
#define IDC_LIST_TIPS                   1060
#define IDC_LIST_DATA                   1060
#define IDC_COMBO_TYPE                  1061
#define IDC_CHECK_TYPE                  1063
#define IDC_BUTTON_OPEN_PATH            1064
#define IDC_STATIC_PATH                 1065
#define IDC_EDIT_PRO_PATH               1066
#define IDC_COMBO1                      1067
#define IDC_COMBO_JOINT_NAME            1067
#define IDC_COMBO_ASSEMBLEY_NO          1067
#define IDC_STATIC_PICTURE              1068
#define IDC_COMBO2                      1068
#define IDC_COMBO_LEFT_JOINT            1068
#define IDC_COMBO3                      1069
#define IDC_COMBO_RIGHT_JOINT           1069
#define ID_BUT_ADD                      1070
#define ID_BUT_DEL                      1072
#define IDC_COMBO_NAMES                 1073
#define IDC_BUTTON2                     1075
#define IDC_BUTTON3                     1076
#define IDC_EDIT_TIP                    1077
#define IDC_CHECK1                      1078
#define IDC_BUT_JISHOU_STANDART         1079
#define IDC_CHECK2                      1080
#define IDC_STATIC_ASSEMBLEY_NO         1080
#define IDC_BUT_JISHOU_STANDART2        1081
#define IDC_STATIC_LEFT_JOINT           1081
#define IDC_CHECK3                      1082
#define IDC_STATIC_RIGHT_JOINT          1082
#define IDC_BUT_JISHOU_STANDART3        1083
#define IDEDIT                          1083
#define IDC_STATIC_TEXT2                1084
#define IDC_EDIT_CHAR                   1085
#define IDC_EDIT_ROW_NUM                1086
#define IDC_STATIC_TEXT3                1086
#define IDC_EDIT_ROW_DIS                1087
#define IDC_BUT_SAVE_PATH               1088
#define IDC_EDIT_FILE_PATH              1089
#define IDC_EDIT_TEXT_SCALE             1090
#define IDC_EDIT_TEXT_SCALE_EXPORT      1091
#define IDC_IPADDRESS_SERVER            1092
#define IDC_LIST_SEC                    1113
#define IDC_LIST_TYPE                   1113
#define IDC_LIST_KEY                    1114
#define IDC_EDIT_USER                   1121
#define IDC_CHECK_L_TYPE                1137
#define IDC_TAB_SHEET                   1145
#define IDC_CHECK_START_OFFSET          1148
#define IDC_CHECK_DIM_KIND              1149
#define IDC_CHECK_START_DIM_LENGTH      1150
#define IDC_CHECK_END_OFFSET            1151
#define IDC_COMBO_ARROW_POS             1152
#define IDC_CHECK_END_DIM_LENGTH        1152
#define IDC_COMBO_ARROW_NUM             1153
#define IDC_COMBO_ARROW_KIND            1155
#define IDC_CHECK_L_COLOR               1156
#define IDC_CHECK_ARROW_POS             1157
#define IDC_CHECK_ARROW_KIND            1158
#define IDC_CHECK_FONT_STYLE            1158
#define IDC_CHECK_ARROW_LEVEL           1159
#define IDC_EDIT_ARROW_LEVEL            1161
#define IDC_CHECK_ARROW_NUM             1163
#define IDC_CHECK_TEXT                  1164
#define IDC_CHECK_TEXT_COLOR            1165
#define IDC_CHECK_TEXT_HIGHT            1166
#define IDC_CHECK_TEXT_ANGLE            1167
#define IDC_CHECK_FRAME_KIND            1168
#define IDC_CHECK_OUT_FRAME             1169
#define IDC_CHECK_FRAME_COLOR           1170
#define IDC_CHECK_PRECISION             1171
#define IDC_CHECK_WIDTH_FACTOR          1172
#define IDC_CHECK_L_RADIUS              1175
#define IDC_EDIT_RADIUS                 1176
#define IDC_COMBO_FRAME_KIND            1177
#define IDC_COMBO_FRAME_OUT             1178
#define IDC_EDIT_HIGHT                  1179
#define IDC_EDIT_START_OFFSET           1182
#define IDC_EDIT_END_OFFSET             1183
#define IDC_EDIT_START_DIM_LEN          1184
#define IDC_EDIT_END_DIM_LEN            1185
#define IDC_COMBO_FRAME_COLOR           5002
#define ID_ARRAY_CAD                    5111
#define IDD_DLG_LAYER_DB                5112
#define IDD_DLG_INPUT                   5113
#define IDD_TAB_ENTITY                  5114
#define IDD_PAGE_ARROW                  5115
#define IDD_PAGE_RADIUS                 5116
#define IDD_PAGE_TEXT                   5117
#define IDD_PAGE_DIM                    5118
#define IDD_DLG_HOT_KEY                 5119
#define IDD_DLG_SELECT_COLOR            5120
#define IDD_DLG_SETTING                 5121
#define IDD_PAGE_DIM_TEXTS              5122
#define IDD_DLG_DIM_TEXTS_EDIT          5123
#define IDD_DLG_FIND_TOOL               5124
#define IDD_DLG_JOINT_EDIT_DB           5125
#define IDD_DLG_TIP_INFO                5126
#define IDD_DLG_AUTO_CHECK              5127
#define IDD_DLG_JISHOU_CHECK            5128
#define IDD_DLG_JISHOU_ADD              5129
#define IDD_DLG_REPLACE_MATERIAL        5130
#define IDD_PAGE_TEXT_COMMON            5131
#define IDD_DLG_SERVER                  5132
#define IDC_COMBO_COLOR                 5136
#define IDC_COMBO_COLOR_NO2             5137
#define IDC_COMBO_COLOR_FILE_0          5137
#define IDC_COMBO_COLOR_FILE_1          5138
#define IDC_COMBO_COLOR_ERROR           5138
#define ID_BUT_ONE_IN                   30012
#define ID_BUT_ONE_IN_P                 30012
#define ID_BUT_REVERSE_COLOR            30013
#define ID_BUT_REVERSE_COLOR_P          30013
#define ID_MENU_SET_COMPLATE_CHECK      32430
#define ID_MENU_SET_COMPLATE_CHECK_P    32430
#define ID_BUT_OPEN_PROJECT             32771
#define ID_BUT_LOGIN                    32772
#define ID_BUT_INPUT_DXFS               32773
#define ID_BUT_LAYER_PART               32774
#define ID_BUT_LAYER_SHEET              32775
#define ID_BUT_LAYER_CUT                32776
#define ID_BUT_LAYER_VIEW               32777
#define ID_BUT_LAYER_DIM                32778
#define ID_BUT_LAYER_MARK               32779
#define ID_BUT_LAYER_APDIM              32780
#define ID_BUT_INSERT_BLOCK             32781
#define ID_MENU_IMPORT_DXF              32781
#define ID_BUT_SAVE_BLOCK               32782
#define ID_BUT_LOAD_LAYER_P             32782
#define ID_BUT_LOAD_LAYER               32783
#define ID_BUT_CLEAR                    32784
#define ID_BUT_CAD_WW                   32785
#define ID_BUT_CAD_EE                   32786
#define ID_BUT_CREATE_TABLE             32787
#define ID_BUT_CREATE_XZ                32788
#define ID_BUT_MERGE_NAME               32789
#define ID_BUT_CUT_TABLE                32790
#define ID_MENU_SET_COMPLATE            32791
#define ID_BUT_SETUP                    32792
#define ID_BUT_SAVE_SERVER              32793
#define ID_BUT_OPEN_SERVER              32794
#define ID_MENU_ORTHO                   32795
#define ID_TOOL_COMBO                   32795
#define ID_MENU_END_PT                  32796
#define ID_BUT_MIRROR                   32797
#define ID_BUT_UNDO                     32798
#define ID_BUT_REDO                     32799
#define ID_BUT_ORTHO                    32800
#define ID_MENU_POINT                   32801
#define ID_BUT_SANP_END_PT              32802
#define ID_BUT_SANP_CROSS_PT            32803
#define ID_BUT_SANP_LINE_PT             32804
#define ID_BUT_SANP_MID_PT              32805
#define ID_BUT_SANP_PERPENDICULAR       32806
#define ID_BUT_SNAP_CIRCLE_PT           32807
#define ID_BUT_SANP_PT                  32808
#define ID_BUT_SANP_ALL                 32809
#define ID_BUT_SHOW_ALL_P               32810
#define ID_BUT_LINE                     32811
#define ID_BUT_ERASE                    32812
#define ID_BUT_MOVE                     32813
#define ID_BUT_COPY                     32814
#define ID_BUT_ROTATE                   32815
#define ID_BUT_SCALE                    32816
#define ID_BUT_HOR                      32816
#define ID_BUT_LAYOUT_DIM_LINE          32817
#define ID_BUT_MOVE_DIM_LINE            32818
#define ID_BUT_DIM_ORTHO_CLOSED         32819
#define ID_BUT_DIM_ALIGN_CLOSED         32820
#define ID_BUT_DIM_ANGLE                32821
#define ID_BUT_DIM_RADIUS               32822
#define ID_BUT_DIM_RE0                  32823
#define ID_BUT_DIM_LEAD_INFO            32824
#define ID_BUT_IMPORT_NAME_INFO         32825
#define ID_BUT_DIM_NAME_SET             32826
#define ID_MENU_NEW_FEATURES            32827
#define ID_BUT_DIM_LINE_DIRECT          32828
#define ID_BUT_DIM_NAME_NOlLINE         32829
#define ID_BUT_SET_REPLACE_SIGN         32830
#define ID_BUT_EXTEND                   32832
#define ID_BUT_DIM_LINE_PLATE_SIDE      32835
#define ID_BUT_DECOMPOSE                32836
#define ID_BUT_CREATE_BLOCK_NEW         32837
#define ID_BUT_TRIM                     32839
#define ID_BUT_OFFSET                   32840
#define ID_BUT_CUT_DIM_LINE             32841
#define ID_MENU_COPY                    32842
#define ID_FILE_IMPORT_DXF              32842
#define ID_BUT_ADD_DIM                  32843
#define ID_FILE_OUTPORT_DXF             32843
#define ID_BUT_DEL_DIM                  32844
#define ID_FILE_OPEN_LUA                32844
#define ID_BUT_LAYOUT_DIM_BASE          32845
#define ID_FILE_SAVE_LUA                32845
#define ID_BUT_DIM                      32846
#define ID_MENU_OPEN_DIR                32846
#define ID_MENU_EXIT_CMD                32847
#define ID_MENU_ERASE                   32847
#define ID_MENU_VIEW_COPY               32848
#define ID_MENU_VIEW_PASTE              32849
#define ID_MENU_VIEW_ARRAY              32850
#define ID_MENU_VIEW_ROTATE             32851
#define ID_MENU_VIEW_SCALE              32852
#define ID_MENU_REPEAT                  32853
#define ID_MENU_VIEW_MIRROR             32853
#define ID_MENU_OK                      32854
#define ID_MENU_VIEW_BREAK              32854
#define ID_BUT_RECT                     32855
#define ID_MENU_VIEW_OFFSET             32855
#define ID_BUT_POLYGON                  32856
#define ID_MENU_VIEW_DIM                32856
#define ID_MENU_VIEW_TRIM               32857
#define ID_MENU_VIEW_EXTEND             32858
#define ID_BUT_DIM_ALIGN_PILEUP         32859
#define ID_MENU_VIEW_CUT                32859
#define ID_BUT_DIM_ORTHO_PILEUP         32860
#define ID_MENU_VIEW_MULTI_CUT          32860
#define ID_MENU_VIEW_STRETCHES          32861
#define ID_MENU_VIEW_LINE               32862
#define ID_MENU_VIEW_CIRCLE             32863
#define ID_MENU_VIEW_ARC                32864
#define ID_MENU_VIEW_SPLINE             32865
#define ID_MENU_VIEW_RECT               32866
#define ID_MENU_VIEW_POLYGON            32867
#define ID_MENU_VIEW_DIM_LEAD           32868
#define ID_MENU_VIEW_ORTHO_CLOSED       32869
#define ID_MENU_VIEW_ALIGN_CLOSED       32870
#define ID_MENU_VIEW_ORTHO_PIPEUP       32871
#define ID_MENU_VIEW_ALIGN_PIPEUP       32872
#define ID_MENU_VIEW_DIM_ANGLE          32873
#define ID_BUT_DXF_OUT                  32874
#define ID_MENU_VIEW_DIM_RADIOUS        32874
#define ID_MENU_VIEW_MOVE_DIM           32875
#define ID_MENU_VIEW_MOVE_SIGNE_DIM     32876
#define ID_BUT_ARRAY                    32877
#define ID_MENU_VIEW_ADD_DIM            32877
#define ID_MENU_VIEW_DEL_DIM            32878
#define ID_MENU_VIEW_CUT_DIM_LINE       32879
#define ID_MENU_VIEW_CHANGE_DIM_0       32880
#define ID_MENU_VIEW_TEXT               32881
#define ID_MENU_VIEW_DIM_LEAD_INFO      32882
#define ID_MENU_VIEW_DIM_TEXT_INFO      32883
#define ID_MENU_VIEW_DIM_PLATESIDE      32884
#define ID_MENU_VIEW_DIM_DIRECT_LINE    32885
#define ID_BUT_NEW_VIEW                 32886
#define ID_MENU_VIEW_CUT_DIM_LINE_NO_SIDE 32886
#define ID_MENU_VIEW_CRATE_BLOCK        32887
#define ID_MENU_VIEW_INSERT_BLOCK       32888
#define ID_MENU_VIEW_REPLACE_STRING     32889
#define ID_MENU_VIEW_HOTKEY             32890
#define ID_MENU_VIEW_ORTHO              32891
#define ID_MENU_VIEW_END_PT             32892
#define ID_MENU_VIEW_CROSS_PT           32893
#define ID_MENU_VIEW_PT_IN_LINE         32894
#define ID_MENU_VIEW_MIDDLE             32895
#define ID_MENU_VIEW_PERPENDICULAR      32896
#define ID_MENU_VIEW_CENTER             32897
#define ID_MENU_VIEW_PT                 32898
#define ID_MENU_VIEW_ALL                32899
#define ID_MENU_ADD_VIEW                32900
#define ID_MENU_VIEW_IMPORT_PARTLIST    32900
#define ID_MENU_DELETE_VIEW             32901
#define ID_MENU_VIEW_IMPORT_SET_DIM_NAME_STYLE 32901
#define ID_MENU_EDIT_VIEW               32902
#define ID_BUT_FIND_TOOL                32902
#define ID_BUT_SELECT_HIDE              32903
#define ID_BUTTON32904                  32904
#define ID_MENU_PASTE                   32905
#define ID_BUT_SELECT_SHOWALL           32906
#define ID_BUT_SELECT_SHOW              32907
#define ID_BUT_SELECT_REVERSE_P         32908
#define ID_BUT_SELECT_TABLE_TEXT        32909
#define ID_MENU_OPEN_PROJECT_CHECK      32910
#define ID_MENU_CREATE_PROJECT_CHECK    32911
#define ID_MENU_CREATE_PROJECT          32912
#define ID_MENU_CLOSE_PROJECT_CHECK     32912
#define ID_MENU_OPEN_PROJECT            32913
#define ID_MENU_UPDATE                  32914
#define ID_MENU_CREATE_DXF              32915
#define ID_MENUITEM_SAVE                32916
#define ID_BUT_SELECT_TEXT_SIGNAL       32917
#define ID_MENU_SET_ERROR_CHECK_P       32918
#define ID_MENU_CLEAR_STATUS_           32919
#define ID_BUT_SELECT_JISHOU            32920
#define ID_BUT_DRAW_EXTEND_LINE         32921
#define ID_MENU_CLOSE_PROJECT           32922
#define ID_BUT_JOINTDB                  32922
#define ID_BUT_AUTO_CHECK               32923
#define ID_BUT_REPLACE_MATRAIL          32924
#define ID_BUT_FIND_CENTER              32926
#define ID_BUT_OPEN_PROJECT_PATH        32927
#define ID_BUT_FIND_MID                 32928
#define ID_BUT_DIM_SOLPE                32929
#define ID_BUT_CANCEL_COMBINATION       32930
#define ID_MENU_SETUP                   32931
#define ID_BUT_MULTIBREAK               32946
#define ID_MENU_PROP                    32952
#define ID_BUT_STRETCHES_P              32958
#define ID_MENU_PREPENDICULIAR_WP       33001
#define ID_TOOL_SHOW_LAYER              33002
#define ID_TOOL_SHOW_LAYER_P            33002
#define ID_BUT_SELECT_FILE_0_P          33002
#define ID_TOOL_LOCK_LAYER              33003
#define ID_TOOL_LOCK_LAYER_P            33003
#define ID_TOOL_SELECT                  33004
#define ID_TOOL_SELECT_P                33004
#define ID_BUT_DIM_TXT                  33005
#define ID_BUT_DIM_TXT_P                33005
#define ID_BUT_HOT_KEY                  33006
#define ID_BUT_HOT_KEY_P                33006
#define ID_BUT_IN_LUA                   33010
#define ID_BUT_IN_LUA_P                 33010
#define ID_BUT_OUT_LUA                  33011
#define ID_BUT_OUT_LUA_P                33011
#define ID_BUT_CHECK_TEXT               33012
#define ID_BUT_CHECK_TEXT_P             33012
#define ID_BUT_SELECT_TEXT              33013
#define ID_BUT_SELECT_TEXT_P            33013
#define ID_BUT_SHOW_SAME_TEXT           33014
#define ID_BUT_SHOW_SAME_TEXT_P         33014
#define ID_BUT_CREATE_REPORT            33015
#define ID_BUT_CREATE_REPORT_P          33015
#define ID_BUTTON32812                  33020
#define ID_BUTTON32812_P                33020
#define ID_APP_HELP                     33022
#define ID_APP_HELP_P                   33022
#define ID_BUT_COMPARE_XSTEEL           33023
#define ID_BUT_COMPARE_XSTEEL_P         33023
#define ID_BUT_SELECT_FILE_0            33031
#define ID_BUT_SELECT_FILE_01           33031
#define ID_BUT_BRUSH                    33032
#define ID_BUT_BRUSH_P                  33032
#define ID_BUT_FILE_MAMAGE              33033
#define ID_BUT_FILE_MAMAGE_p            33033
#define ID_BUT_CIRCLE_P                 40000
#define ID_BUT_ARC_P                    40001
#define ID_BUT_SPLINE                   40002
#define ID_BUT_DIM_LEAD                 40003
#define ID_BUT_DXF_IN                   40005
#define ID_MENU_MOVE                    40010
#define ID_MENU_DELETE                  40011
#define ID_MENU_CROSS_P                 40019
#define ID_MENU_PT_IN_LINE              40020
#define ID_MENU_MIDDLE                  40021
#define ID_MENU_SNAP_ALL                40022
#define ID_BUT_INSERT_BLOCK111          40024
#define ID_BUT_INSERT_BLOCK222          40024
#define ID_BUT_INSERT_BLOCK_P222P       40025
#define ID_BUT_SELECT_REVERSE           40100
#define ID_BUT_TRIM_CAD_P               41028
#define ID_BUT_HOTKEY_REI               50000
#define ID_BUT_BREAK_P                  61447
#define ID_BUT_PASTE                    61448
#define ID_EDIT_TEXT_VAL                65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32932
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
