database {
	dimensionstylelist_ = { 
		{
			kind = [[Dimension_Style]],
			name_ = [[Standard]],
			text_style_ = [[Standard]],
			text_precision_ = 0.01,
			decimal_place_ = 2,
			decimal_addends_ = 0,
			extendstartoff_ = 0.5,
			extendendoff_ = 3,
			start_dim_length_ = 8,
			end_dim_length_ = 8,
			arrowstyle_ = 10,
			arrowsize_ = 2,
			arrow_num_ = 0,
			tf_ = 1,
			tp_ = 20,
			text_hight_ = 25,
			text_frame_color_ = 1,
			text_color_ = 1,
			line_color_ = 1,
		},
	},
	entlist_ = { 
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3763.935,
				y = 5753.79,
				z = 0,
			},
			ed_ = { 
				x = 3763.935,
				y = 5678.79,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3763.935,
				y = 4902.825,
				z = 0,
			},
			ed_ = { 
				x = 3763.935,
				y = 4977.825,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3763.935,
				y = 5753.79,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 5753.79,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3711.435,
				y = 5765.04,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 5753.79,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3711.435,
				y = 5742.54,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 5753.79,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3763.935,
				y = 4902.825,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 4902.825,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3711.435,
				y = 4914.075,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 4902.825,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3711.435,
				y = 4891.575,
				z = 0,
			},
			ed_ = { 
				x = 3688.935,
				y = 4902.825,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[E]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3709.56,
				y = 5690.04,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[E]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3709.56,
				y = 4921.575,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 5637.885,
				z = 0,
			},
			ed_ = { 
				x = 2550.525,
				y = 5637.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 5637.885,
				z = 0,
			},
			ed_ = { 
				x = 3905.85,
				y = 5637.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 5637.885,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2464.275,
				y = 5585.385,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2486.775,
				y = 5585.385,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 5637.885,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3969.6,
				y = 5585.385,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3992.1,
				y = 5585.385,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 5562.885,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[D]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 2494.275,
				y = 5577.885,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[D]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3928.35,
				y = 5577.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 4761.885,
				z = 0,
			},
			ed_ = { 
				x = 2550.525,
				y = 4761.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 4761.885,
				z = 0,
			},
			ed_ = { 
				x = 3905.85,
				y = 4761.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 4761.885,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2464.275,
				y = 4709.385,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2486.775,
				y = 4709.385,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 4761.885,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3969.6,
				y = 4709.385,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3992.1,
				y = 4709.385,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4686.885,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[C]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 2494.275,
				y = 4701.885,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[C]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3928.35,
				y = 4701.885,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 4086.39,
				z = 0,
			},
			ed_ = { 
				x = 2550.525,
				y = 4086.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 4086.39,
				z = 0,
			},
			ed_ = { 
				x = 3905.85,
				y = 4086.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 4086.39,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2464.275,
				y = 4033.89,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2486.775,
				y = 4033.89,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 4086.39,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3969.6,
				y = 4033.89,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3992.1,
				y = 4033.89,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 4011.39,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[B]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 2494.275,
				y = 4026.39,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[B]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3928.35,
				y = 4026.39,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 1861.89,
				z = 0,
			},
			ed_ = { 
				x = 2550.525,
				y = 1861.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 1861.89,
				z = 0,
			},
			ed_ = { 
				x = 3905.85,
				y = 1861.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2475.525,
				y = 1861.89,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2464.275,
				y = 1809.39,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 2486.775,
				y = 1809.39,
				z = 0,
			},
			ed_ = { 
				x = 2475.525,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3980.85,
				y = 1861.89,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3969.6,
				y = 1809.39,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 3992.1,
				y = 1809.39,
				z = 0,
			},
			ed_ = { 
				x = 3980.85,
				y = 1786.89,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[A]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 2494.275,
				y = 1801.89,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[A]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3928.35,
				y = 1801.89,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[•Õ•√•»•’•√•Ø•¶•ÈÇ»»°∏∂]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 3887.33830446437,
				y = 5278.48537351657,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[CUT]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[œ»––•·•√•≠]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 2494.275,
				y = 4970.38800465331,
				z = 0,
			},
		},
	},
}
