database {
	dimensionstylelist_ = { 
		{
			kind = [[Dimension_Style]],
			name_ = [[Standard]],
			text_style_ = [[Standard]],
			text_precision_ = 0.01,
			decimal_place_ = 2,
			decimal_addends_ = 0,
			extendstartoff_ = 0.5,
			extendendoff_ = 3,
			start_dim_length_ = 8,
			end_dim_length_ = 8,
			arrowstyle_ = 10,
			arrowsize_ = 2,
			arrow_num_ = 0,
			tf_ = 1,
			tp_ = 20,
			text_hight_ = 25,
			text_frame_color_ = 1,
			text_color_ = 1,
			line_color_ = 1,
		},
	},
	entlist_ = { 
		{
			kind = [[Circle]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[0]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 255,
				blue = 255,
			},
			radius_ = 281.23164831937,
			center_ = { 
				x = 3234.195,
				y = 5395.815,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[0]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 255,
				blue = 255,
			},
			st_ = { 
				x = 1214.3954622728,
				y = 5553.135,
				z = 0,
			},
			ed_ = { 
				x = 1214.3954622728,
				y = 1768.14,
				z = 0,
			},
		},
	},
}
