database {
	dimensionstylelist_ = { 
		{
			kind = [[Dimension_Style]],
			name_ = [[Standard]],
			text_style_ = [[Standard]],
			text_precision_ = 0.01,
			decimal_place_ = 2,
			decimal_addends_ = 0,
			extendstartoff_ = 0.5,
			extendendoff_ = 3,
			start_dim_length_ = 8,
			end_dim_length_ = 8,
			arrowstyle_ = 10,
			arrowsize_ = 2,
			arrow_num_ = 0,
			tf_ = 1,
			tp_ = 20,
			text_hight_ = 25,
			text_frame_color_ = 1,
			text_color_ = 1,
			line_color_ = 1,
		},
	},
	entlist_ = { 
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[A - A]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 8340.405,
				y = 1543.44,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 8340.405,
				y = 1534.44,
				z = 0,
			},
			ed_ = { 
				x = 8509.155,
				y = 1534.44,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[B - B]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 8263.62,
				y = 2566.74,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 8263.62,
				y = 2557.74,
				z = 0,
			},
			ed_ = { 
				x = 8432.37,
				y = 2557.74,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[C - C]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 8375.46,
				y = 3383.865,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 8375.46,
				y = 3374.865,
				z = 0,
			},
			ed_ = { 
				x = 8544.21,
				y = 3374.865,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[D - D]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 8163.285,
				y = 4250.29111907313,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 8153.38917415478,
				y = 4241.29111907313,
				z = 0,
			},
			ed_ = { 
				x = 8332.035,
				y = 4241.29111907313,
				z = 0,
			},
		},
		{
			kind = [[Text]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			align_point_ = 3,
			content_ = [[E - E]],
			style_name_ = [[Standard]],
			width_factor_ = 1,
			dxf_height_ = 45,
			rotation_radian_ = 0,
			postion_ = { 
				x = 4456.32899290239,
				y = 4609.96910524307,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[VIEW]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			st_ = { 
				x = 4456.32899290239,
				y = 4600.96910524307,
				z = 0,
			},
			ed_ = { 
				x = 4625.07899290239,
				y = 4600.96910524307,
				z = 0,
			},
		},
	},
}
