database {
	dimensionstylelist_ = { 
		{
			kind = [[Dimension_Style]],
			name_ = [[Standard]],
			text_style_ = [[Standard]],
			text_precision_ = 0.01,
			decimal_place_ = 2,
			decimal_addends_ = 0,
			extendstartoff_ = 0.5,
			extendendoff_ = 3,
			start_dim_length_ = 8,
			end_dim_length_ = 8,
			arrowstyle_ = 10,
			arrowsize_ = 2,
			arrow_num_ = 0,
			tf_ = 1,
			tp_ = 20,
			text_hight_ = 25,
			text_frame_color_ = 1,
			text_color_ = 1,
			line_color_ = 1,
		},
	},
	entlist_ = { 
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 8361.63,
				y = 2738.355,
				z = 0,
			},
			ed_ = { 
				x = 8361.63,
				y = 2766.675,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 8515.95,
				y = 2841.675,
				z = 0,
			},
			ed_ = { 
				x = 8620.14,
				y = 2841.675,
				z = 0,
			},
		},
		{
			kind = [[RArc]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			start_pt = { 
				x = 5523.865,
				y = 5553.135,
				z = 0,
			},
			path_pt = { 
				x = 5513.865,
				y = 5563.135,
				z = 0,
			},
			end_pt = { 
				x = 5503.865,
				y = 5553.135,
				z = 0,
			},
		},
		{
			kind = [[RArc]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 255,
				green = 0,
				blue = 255,
			},
			start_pt = { 
				x = 5503.865,
				y = 5553.135,
				z = 0,
			},
			path_pt = { 
				x = 5513.865,
				y = 5543.135,
				z = 0,
			},
			end_pt = { 
				x = 5523.865,
				y = 5553.135,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 3104.925,
				y = 1556.055,
				z = 0,
			},
			ed_ = { 
				x = 3365.67,
				y = 1556.055,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 3320.67,
				y = 1541.055,
				z = 0,
			},
			ed_ = { 
				x = 3365.67,
				y = 1556.055,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 3320.67,
				y = 1571.055,
				z = 0,
			},
			ed_ = { 
				x = 3365.67,
				y = 1556.055,
				z = 0,
			},
		},
		{
			kind = [[Line]],
			seled_ = 0,
			visibility_ = 1,
			linewidth_ = 1,
			linestyle_ = [[Continuous]],
			layername_ = [[LINE]],
			group_ = [[]],
			real_color_ = 1,
			color_ = { 
				red = 0,
				green = 255,
				blue = 0,
			},
			st_ = { 
				x = 8721.315,
				y = 5019.31585295595,
				z = 0,
			},
			ed_ = { 
				x = 8762.28,
				y = 5019.31585295595,
				z = 0,
			},
		},
	},
}
